### ISSUE TITLE
App still crashing

### ISSUE THREAD

**Issue by Eragos** [mro/ShaarliOS#5] opened 2015-10-10 11:25 UTC
I moved to another Shaali url with an valid SSL certificate. When I try to change the URL in ShaarliOS the App crashes every time.

I tried the following things without success:
* Connect via HTTP instead of HTTPS
* Completely remove the App from the phone. After reinstall, the Settings are still there.

**Comment by mro** [comment] 2015-10-10 11:37
can you give details about

- the procedure you apply (in other words: plz describe what precisely you do),
- the shaarli version you use,
- what template?

The App shouldn't ever crash, naturally, but in the worst case give an error message.

**Comment by Eragos** [comment] 2015-10-10 12:00
Thanks for the quick reply. Here are my Steps:

1. Startung ShaaliOS
2. Enter Settings Dialog
3. Change Hostname
4. Change to HTTPS
5. Press Done
6. Crash

I send you the console log and crash report to your personal mail.

**Comment by mro** [comment] 2015-10-12 06:58
the bug is triggered by a `div` tag without attributes in the response html.

Until the fixed version is through the App Review, you can workaround by adding a dummy attribute to all `div`and `span` tags in your custom template, e.g. `<div class=''>...`

@Eragos Can you confirm this prevents the crash?

Thank you for your patience.

**Comment by mro** [comment] 2015-11-04 22:02
ping @Eragos ?

**Comment by joedemo42** [comment] 2016-01-15 13:23
Well, since he doesn't answer, let me do.

Ensuring that there are no div/span tags without attributes fixes this.
**BUT**: This was not caused by a custom template - at least not in my case.
In my case two of the included plugins added empty spans. The culprits were/are `plugins/qrcode` and `plugins/archiveorg`. The latter one is easily fixed by editing `plugins/archiveorg/archiveorg.html`, but at the first glance, I've no idea where `plugins/qrcode` get's its empty `span` from

I guess since `plugins/qrcode` is enabled by default in shaarli/Shaarli@92ba7b573f2833bd35c7eb2fc7fdbeb1a0ac7b44 your claim of being compatible with "all functional Shaarli versions" is not exactly true. ;-)

**Comment by mro** [comment] 2016-01-15 18:33
@joedemo42 sorry for the incenvenience, the claim holds, it's a plain bug here.

The fix went into review by Apple today, so expect it within the next days.

**Comment by mro** [comment] 2016-01-15 18:38
@joedemo42 is your version mentioned at https://travis-ci.org/mro/Shaarli-API-test/builds/94725334 as successful build?

**Comment by joedemo42** [comment] 2016-01-15 18:49
Umm.... I have to admit, I really am not sure how to check Travis-CI for this.

I cloned the master of Shaarli yesterday, and since the latest commit was 4 days ago, I figured it would be OK to reference the hash of this commit. Hope this helps.

**Comment by mro** [comment] 2016-01-15 20:27
@joedemo42 I mean the Shaarli backend version, not the ShaarliOS client one.

**Comment by joedemo42** [comment] 2016-01-15 20:29
@mro so do I.

**Comment by mro** [comment] 2016-01-15 20:38
ic, good, where from did you get the backend php sources? (download link?)

**Comment by joedemo42** [comment] 2016-01-15 20:42
Well, as I said: i cloned them. Right from the github repo.

git clone https://github.com/shaarli/Shaarli

**Comment by mro** [comment] 2016-01-15 21:40
ok, good news then – the fix is in review and will be available within <1week. This is the relevant code change: 87008e4cf6

**Comment by mro** [comment] 2016-01-20 12:55
version 1.0.2 was rejected by Apple for *"App name contains information not relevant to content and functionality (iOS)"* and *"Specifically, your app description does not describe the functionality of the app."* referring to a screenshot of the settings screen inside the app (yes, really).

I'm in contact with the appreviewboard.

**Comment by joedemo42** [comment] 2016-01-20 16:29
This is pretty ridiculous.

**Comment by mro** [comment] 2016-01-20 21:56
meanwhile the first issue was dropped but the name issue remains.

I'm thinking about new names now, maybe *ShaarliO2' :-)

**Comment by mro** [comment] 2016-01-20 21:57
meanwhile the 2nd issue was dropped but the name issue remains.

I'm thinking about new names now, maybe *ShaarliO2* or *Shaarlios* :-)

**Comment by joedemo42** [comment] 2016-01-20 22:07
I'd vote for Shaarlios.

**Comment by mro** [comment] 2016-01-20 22:25
side note: *IOS is a trademark or registered trademark of Cisco in the U.S. and other countries and is used under license.* http://www.apple.com/legal/intellectual-property/trademark/appletmlist.html

**Comment by joedemo42** [comment] 2016-01-21 09:27
On a second thought: how about Shaarlite, since it's a "lite" client, not a full one?

**Comment by mro** [comment] 2016-01-21 10:21
indeed. Or *ShaarliEx* as it's a share app extension. But I'd like to keep the old name as it is platform specific exactly as the app is.

**Comment by mro** [comment] 2016-02-01 11:50
started another try at Apple, new App Name is "Shaarli💫" or ShaarliO in non-unicode environments.

**Comment by mro** [comment] 2016-02-02 21:09
open until fix available in App Store

**Comment by mro** [comment] 2016-02-08 11:41
after Apple rejected again (3rd time now) – this time for "App crashing" and mentioning the App name change due to Apple in the release notes – I'm doing the feature release 1.1 now.

Just submitted moments ago. Fingers crossed.

**Comment by mro** [comment] 2016-02-16 08:32
fixed in v1.1 9b428a6

**Closed by mro** 2016-02-16 08:32 UTC
Labels: bug
