### ISSUE TITLE
Problem with firefox 

### ISSUE THREAD

**Issue by ParoTheParrot** [mro/ShaarliOS#24] opened 2020-03-25 07:23 UTC
The new version does not work for me: neither with iOS firefox nor safari: no new entry thru the share dialog!
Submitting a new entry with the app itself works!

**Comment by mro** [comment] 2020-03-26 06:57
Thank you for reporting, I'll look into it immediately.

**Comment by mro** [comment] 2020-03-26 06:58
Can you elaborate on iOS, Safari & Firefox versions and an example link?

**Comment by mro** [comment] 2020-03-26 07:07
Can you do me a favour and try the backend at https://demo.0x4c.de/shaarli-v0.41b/?E7g76Q with did: demo and pwd: demodemodemo

**Comment by mro** [comment] 2020-03-26 07:19
How can we find out what's special with your setup – https://demo.shaarli.org/?WgYmTw also works find.

**Comment by ParoTheParrot** [comment] 2020-03-26 07:54
> Can you do me a favour and try the backend https://demo.0x4c.de/shaarli-v0.41b/ with uid: demo and pwd: demodemodemo
Same situation as described  [here](https://github.com/mro/ShaarliOS/issues/24#issue-587494220)

**Comment by ParoTheParrot** [comment] 2020-03-26 07:55
> Can you elaborate on iOS, Safari & Firefox versions and an example link?

newest versions (up to date)

**Comment by mro** [comment] 2020-03-26 19:43
@ParoTheParrot can you explain how https://demo.0x4c.de/shaarli-v0.41b/?qnvnNg cme to be? It looks like you modified it. How did you do that?

**Comment by ParoTheParrot** [comment] 2020-03-27 06:29
> @ParoTheParrot can you explain how https://demo.0x4c.de/shaarli-v0.41b/?qnvnNg came to be? It looks like you modified it. How did you do that?

I submitted a new entry in the shaarli iOS app

**Comment by ParoTheParrot** [comment] 2020-03-27 06:39
BTW : I use  the newest Shaarli https://github.com/shaarli/Shaarli/releases/tag/v0.11.1

**Comment by mro** [comment] 2020-03-27 06:49
> > @ParoTheParrot can you explain how https://demo.0x4c.de/shaarli-v0.41b/?qnvnNg came to be? It looks like you modified it. How did you do that?
> 
> I submitted a new entry in the shaarli iOS app

how did you enter the URL?

**Comment by ilPeo** [comment] 2020-03-28 20:53
> The new version does not work for me: neither with iOS firefox nor safari: no new entry thru the share dialog!
> Submitting a new entry with the app itself works!

I have the same issue:
iOS 12.4.5 , I’m running Shaarli 0.11.
Everything was OK until the new app update.
I tried reinstalling it and re-entering all the settings.

**Comment by mro** [comment] 2020-03-31 10:31
@ParoTheParrot and @ilPeo there's a new version, could you please check that the problem is resolved? https://apps.apple.com/de/app/shaarlios/id1027441388 Thx!

**Comment by ilPeo** [comment] 2020-03-31 14:34
Now I hear a sound when I submit a link, but nothing else happens.
I'm willing to help, if you need.
Thanks

**Comment by mro** [comment] 2020-03-31 18:07
@ilPeo can you enter the backend from https://github.com/mro/ShaarliOS/issues/24#issuecomment-604266165 - that's a server of mine where I can inspect the server logs. The precise time also would be great. Thx!

**Comment by ilPeo** [comment] 2020-04-01 08:22
I just sent an URL, it’s 10.20 AM here in Italy

**Comment by mro** [comment] 2020-04-01 09:06
hm, looks good, doesn't it? https://demo.0x4c.de/shaarli-v0.41b/?uFuNFQ

So the issue may be your server. (Nevertheless you should **Aalways** see the post once you heard the sound).

Can you post a note (from the ShaarliOS App) to you server?

**Comment by ilPeo** [comment] 2020-04-01 16:54
> hm, looks good, doesn't it? https://demo.0x4c.de/shaarli-v0.41b/?uFuNFQ (Edit: Purged meanwhile, please repost)
> 
> So the issue may be your server. (Nevertheless you should **Aalways** see the post once you heard the sound).
Maybe, but it's strange because I never had any issue with the old version of the app.
Do you mean that I should see the post **in the app** after it has send it to my server? I never see anything.

I'll try to upgrade my Shaarli server as soon as possible and let you know but I read the @ParoTheParrot has the same problem with the latest Shaarli release, so I have little hope.

Thanx

> 
> Can you post a note (from the ShaarliOS App) to you server?
I tried, it failed. I always hear the noise but nothing get saved.

**Comment by ParoTheParrot** [comment] 2020-04-02 05:44
> @ParoTheParrot and @ilPeo there's a new version, could you please check that the problem is resolved? https://apps.apple.com/de/app/shaarlios/id1027441388 Thx!

With the new version I got a popup message "Error. Got no respose body" and no new entry.

**Comment by mro** [comment] 2020-04-02 06:45
@ParoTheParrot I apologize for the annoyance and will submit a new version (1.2.2) later today.

Is the "response body" issue still Firefox only?

**Comment by mro** [comment] 2020-04-03 08:38
@ParoTheParrot @ilPeo the v1.2.2 just came out, do you want to check and give feedback? Thanks!

P.S.: I'd be happy if you [rate the App](https://apps.apple.com/de/app/shaarlios/id1027441388?mt=8&action=write-review).

**Comment by ilPeo** [comment] 2020-04-03 09:21
> @ParoTheParrot @ilPeo the v1.2.2 just came out, do you want to check and give feedback? Thanks!
> 
> P.S.: I'd be happy if you [rate the App](https://apps.apple.com/de/app/shaarlios/id1027441388?mt=8&action=write-review).

Thanks, but the issue is still there :-(

**Comment by ParoTheParrot** [comment] 2020-04-03 11:41
> @ParoTheParrot I apologize for the annoyance and will submit a new version (1.2.2) later today.
> Is the "response body" issue still Firefox only?

nothing new :-(

**Comment by mro** [comment] 2020-04-03 11:45
@ParoTheParrot @ilPeo can you both please use the backend server at https://demo.0x4c.de/shaarli-v0.11.1/ with user `demo` and password `demodemodemo` both posting a note from the app and share a url from firefox?

Please forgive me not trusting 3rd-party private servers.

**Comment by ilPeo** [comment] 2020-04-05 07:42
> > @ParoTheParrot I apologize for the annoyance and will submit a new version (1.2.2) later today.
> > Is the "response body" issue still Firefox only?
> 
> nothing new :-(

Just something that came to my mind: could it be anything related to PHP? I recently upgraded to PHP 7.4 .
Which version are you running, @ParoTheParrot @mro ?

**Comment by mro** [comment] 2020-04-06 06:15
@ParoTheParrot @ilPeo sorry for the inconvenience, but could you please once repeat the test from https://github.com/mro/ShaarliOS/issues/24#issuecomment-608388975 – a forgotten cron-job purged the demo backend early this morning.

Thanks for your patience and help!

**Comment by ParoTheParrot** [comment] 2020-04-06 06:40
> > > @ParoTheParrot I apologize for the annoyance and will submit a new version (1.2.2) later today.
> > > Is the "response body" issue still Firefox only?
> > 
> > 
> > nothing new :-(
> 
> Just something that came to my mind: could it be anything related to PHP? I recently upgraded to PHP 7.4 .
> Which version are you running, @ParoTheParrot @mro ?
> 
> EDITED:
> Nevermind, I tried reverting back to PHP 7.3 with no changes.

I use 7.3

**Comment by ParoTheParrot** [comment] 2020-04-06 06:42
> @ParoTheParrot @ilPeo can you both please use the backend server at https://demo.0x4c.de/shaarli-v0.11.1/ with user `demo` and password `demodemodemo` both posting a note from the app and share a url from firefox?
> 
> Please forgive me not trusting 3rd-party private servers.
https://demo.0x4c.de/shaarli-v0.11.1/?JORd-w

**Comment by mro** [comment] 2020-04-06 08:32
@ParoTheParrot 

> https://demo.0x4c.de/shaarli-v0.11.1/?JORd-w

hm, the demo server seems to do the job. As I cannot see the server you have to issue with, any idea what could be a relevant difference to the demo backend?

**Comment by ilPeo** [comment] 2020-04-06 12:17
> @ParoTheParrot
> 
> > https://demo.0x4c.de/shaarli-v0.11.1/?JORd-w
> 
> hm, the demo server seems to do the job. As I cannot see the server you have the issue with, any idea what could be a relevant difference to the demo backend?

I've been hosting my Shaarli instance on the same shared hosting without any issue for a few years.
No special configuration, I usually download the latest Shaarli release, unpack it and get it running.
What should I look for to make things clearer for you @mro ?

**Comment by mro** [comment] 2020-04-06 13:19
That sounds faily common. Some people add additional layers of security, do customize or patch the css/html etc.

**Comment by ilPeo** [comment] 2020-04-06 13:21
> That sounds faily common. Some people add additional layers of security, do customize or patch the css/html etc.

I only forced https

**Comment by mro** [comment] 2020-04-07 09:25
@ParoTheParrot @ilPeo can you please give the v1.2.4 a try, the v1.2.3 was total garbage :-(.

**Comment by ilPeo** [comment] 2020-04-07 10:21
No good news.
One thing I noticed is that the app doesn’t even seem to connect to my server.
I don’t see any spinning wheel like the one attached, just to be clear

**Comment by mro** [comment] 2020-04-07 14:15
As long as I can't see (and use) a server that shows the failure, I have no idea what I could do. I am blind to the problem. Can you clone a failing server and give me access. Use temporary credentials and post them here or even send the endpoint and credentials via [private email](https://github.com/mro/ShaarliOS#bug-reports).

Also I need to positively know what ShaarliOS version you are using.

**Comment by ilPeo** [comment] 2020-04-07 16:25
I’m on 1.24 right now.
I’ll try to setup a clone server as soon as possible.
Is there any specific log I can send you ?

**Comment by mro** [comment] 2020-04-07 19:46
@ilPeo no, not for now. I'll debug into the server responses once I can access it.

**Comment by ilPeo** [comment] 2020-04-08 13:12
here's my .htaccess file, any chance do you find something useful there?
`# Disable directory listing
Options -Indexes

RewriteEngine On

# Prevent accessing subdirectories not managed by SCM
RewriteRule ^(.git|doxygen|vendor) - [F]

# Forward the "Authorization" HTTP header
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

# REST API
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]

<Limit GET POST PUT DELETE OPTIONS>
  <IfModule version_module>
    <IfVersion >= 2.4>
       Require all granted
    </IfVersion>
    <IfVersion < 2.4>
       Allow from all
       Deny from none
    </IfVersion>
  </IfModule>

  <IfModule !version_module>
    Require all granted
  </IfModule>
</Limit>

<LimitExcept GET POST PUT DELETE OPTIONS>
  <IfModule version_module>
    <IfVersion >= 2.4>
       Require all denied
    </IfVersion>
    <IfVersion < 2.4>
       Allow from none
       Deny from all
    </IfVersion>
  </IfModule>

  <IfModule !version_module>
    Require all denied
  </IfModule>
</LimitExcept>
`

**Comment by ilPeo** [comment] 2020-04-08 13:15
Here's my .htaccess file, maybe you find it useful
```
# Disable directory listing
Options -Indexes

RewriteEngine On

# Prevent accessing subdirectories not managed by SCM
RewriteRule ^(.git|doxygen|vendor) - [F]

# Forward the "Authorization" HTTP header
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

# REST API
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]

<Limit GET POST PUT DELETE OPTIONS>
  <IfModule version_module>
    <IfVersion >= 2.4>
       Require all granted
    </IfVersion>
    <IfVersion < 2.4>
       Allow from all
       Deny from none
    </IfVersion>
  </IfModule>

  <IfModule !version_module>
    Require all granted
  </IfModule>
</Limit>

<LimitExcept GET POST PUT DELETE OPTIONS>
  <IfModule version_module>
    <IfVersion >= 2.4>
       Require all denied
    </IfVersion>
    <IfVersion < 2.4>
       Allow from none
       Deny from all
    </IfVersion>
  </IfModule>

  <IfModule !version_module>
    Require all denied
  </IfModule>
</LimitExcept>
```

**Comment by mro** [comment] 2020-04-09 06:25
@ilPeo Thanks, but a failing server backend to use is what I need.

**Comment by ilPeo** [comment] 2020-04-10 08:51
I haven't got the time to setup another Shaarli instance, but in the meanwhile here's my server log just after trying to share a link via the app:
```93.50.167.224 - - [10/Apr/2020:01:35:40 -0700] "POST /Shaarli/ HTTP/1.1" 500 156 "-" "https://mro.name/ShaarliOS" 
93.50.167.224 - - [10/Apr/2020:01:35:55 -0700] "GET /Shaarli/?post=https://ricette.giallozafferano.it/Piadina-Romagnola.html HTTP/1.1" 302 4219 "-" "https://mro.name/ShaarliOS" 
93.50.167.224 - - [10/Apr/2020:01:35:55 -0700] "GET /Shaarli/?do=login&post=https%3A%2F%2Fricette.giallozafferano.it%2FPiadina-Romagnola.html HTTP/1.1" 200 3040 "-" "https://mro.name/ShaarliOS" 
93.50.167.224 - - [10/Apr/2020:01:35:55 -0700] "POST /Shaarli/?do=login&post=https%3A%2F%2Fricette.giallozafferano.it%2FPiadina-Romagnola.html HTTP/1.1" 302 740 "-" "https://mro.name/ShaarliOS" 
93.50.167.224 - - [10/Apr/2020:01:35:55 -0700] "GET /Shaarli/?post=https%3A%2F%2Fricette.giallozafferano.it%2FPiadina-Romagnola.html HTTP/1.1" 200 5945 "-" "https://mro.name/ShaarliOS
```

All attempts failed.

**Comment by mro** [comment] 2020-04-10 21:49
I see the app doesn't explicitly call `.../index.php` but relies on the web server having this as the default document. That's a bug I will fix 'til Tuesday.

Otherwise I see a lot of 200s end 302s which look successful. That's odd.

**Comment by mro** [comment] 2020-04-11 12:55
however, I doubt that `index.php` affects your issue. If the web server tells [`200`](https://tools.ietf.org/html/rfc7231#section-6.3.1) on the final `POST` (see @ilPeo above), there's nothing the App can do about it, if server doesn't show the post.

**Comment by ilPeo** [comment] 2020-04-11 13:15
> however, I doubt that `index.php` affects your issue. If the web server tells [`200`](https://tools.ietf.org/html/rfc7231#section-6.3.1) on the final `POST` (see @ilPeo above), there's nothing the App can do about it, if server doesn't show the post.

What's strange is that nothing has changed on the server, and it continues to work with link added by the browser bookmarklet.
Any idea?

**Comment by mro** [comment] 2020-04-11 14:20
Did you check the posts in doubt aren't private links visible after login only? There's a switch in the App on the settings screen.

**Comment by ilPeo** [comment] 2020-04-11 16:21
> Did you check the posts in doubt aren't private links visible after login only? There's a switch in the App on the settings screen.

yes, I've done it but nothing changed. THX

**Comment by mro** [comment] 2020-04-11 16:37
what precisely have you done? What change have you expected?

**Comment by ParoTheParrot** [comment] 2020-04-12 17:34
Please bring back th old version! This works without an problems for years !

**Comment by mro** [comment] 2020-04-13 08:35
@ParoTheParrot I understand your wish and can feel your pain, but the old App is history for several reasons. Please help me get the issue with your special situation (and so it looks like) sorted out.

Please tell me a backend URL + credentials that I can use and see the problem, so I can debug and possibly fix it.

**Comment by mro** [comment] 2020-04-13 16:19
maybe related https://github.com/shaarli/Shaarli/issues/428#issuecomment-168006494

**Comment by mro** [comment] 2020-04-14 08:36
Apple just approved the v1.2.5 – it should appear in the App Store soon.

@ParoTheParrot & @ilPeo can you please have a look and report if the v1.2.5 solves your problem or give me access to a failing server?

Thank you for your patience nd help getting this issue resolved.

**Comment by ilPeo** [comment] 2020-04-14 08:44
I’ll update as soon as it shows up for updating. 
Thanks


**************************************************
.[dot]coma
frammentario, discontinuo, confuso: un blog
http://www.dotcoma.org
**************************************************

**Comment by ilPeo** [comment] 2020-04-14 09:17
It works now!!
Good job!

Thank you so much

**Comment by mro** [comment] 2020-04-14 09:27
Please [rate the app (click on the device)](https://apps.apple.com/it/app/shaarlios/id1027441388?mt=8&action=write-review), thanks!

**Comment by ilPeo** [comment] 2020-04-14 11:17
Done.

Thank you, keep up the good job.

**Comment by ParoTheParrot** [comment] 2020-04-14 13:22
> Apple just approved the v1.2.5 – it should appear in the App Store soon.
> 
> @ParoTheParrot & @ilPeo can you please have a look and report if the v1.2.5 solves your problem or give me access to a failing server? 
> Thank you for your patience nd help getting this issue resolved.

Now I need https ,  that's the next problem (see new issue)

**Comment by mro** [comment] 2020-04-14 13:25
can we close this issue here?

**Closed** 2020-04-15 05:57 UTC
Labels: bug, question

**Comment by mro** [comment] 2020-04-15 06:41
@ParoTheParrot thank you for your patience, I assume the v1.2.6 finally resolved your issue.

Would you want to [rate the app](https://apps.apple.com/it/app/shaarlios/id1027441388?mt=8&action=write-review)?
