### ISSUE TITLE
App is not working under iOS 11.0.3

### ISSUE THREAD

**Issue by zafai** [mro/ShaarliOS#19] opened 2017-10-29 15:10 UTC
I just bought the App, but it is not working after setting up all information and try to send a link to the server only a error message appears.

Please fix the app. Thank you :+1:

**Comment by mro** [comment] 2017-10-30 18:44
thx for the report and your patience. Can you elaborate on the error message a bit?

**Comment by zafai** [comment] 2017-10-30 19:04
Thanks for the reply. Here is a screenshot from the error message.
It happens when I use the share button in Safari to share it to my shaarli installation.
The Link gets added to the Shaarli installation but there is still this popup.

And maybe you could add a function to directly add tags when sharing a link. :+1: 

![image-1](https://user-images.githubusercontent.com/10008540/32190119-0b8a797e-bdad-11e7-8387-17f3aeda3f00.jpg)

**Comment by mro** [comment] 2017-10-31 08:36
thanks for the screenshot, it's quite interesting. What I can see is, that the app worked and made it to the final check whether the posted link appeared on the shaarli. But it cannot be found.

Can you please
- verify that the link isn't on the shaarli, also not on page 2 or later,
- tell me about the shaarli you use (where did you get it from, version, template if non-default)
- check if your shaarli is one of the green ones at https://travis-ci.org/mro/Shaarli-API-test/builds/268727254

I will then install that version and test it against both App and https://github.com/mro/Shaarli-API-test.

**Comment by mro** [comment] 2017-11-05 09:26
Closing because no feedback. To wrap up:

- app works fine on all iOS versions since 8.0 including the mot recent,
- tags are added as `#mytag` at the beginning of the text description,
- issue is most probably caused by the shaarli template in use not mentioning the posted link after the post.

**Comment by zafai** [comment] 2017-11-05 10:19
Sorry for the late reply, here are the requested information:

1. verify that the link isn't on the shaarli, also not on page 2 or later,
1.1 The Link gets posted on the first page.
2. tell me about the shaarli you use (where did you get it from, version, template if non-default)
2.1 Version 0.9.2, downloaded here https://github.com/shaarli/Shaarli/releases/download/v0.9.2/shaarli-v0.9.2-full.zip Theme is Default
3. check if your shaarli is one of the green ones at https://travis-ci.org/mro/Shaarli-API-test/builds/268727254
3.1 Is not able to find Version 0.9.2 in the list.

For my tag question, in the screenshot, you can see the first entry is added with the web version so the tag is listed in the tag row.
The second entry is posted via the app then the tag is listed in the description field.
Is there maybe a setting that shaarli added `#test` to the tag row?
![image](https://user-images.githubusercontent.com/10008540/32413851-36dc6d50-c21a-11e7-8583-cc6ae41a1c5e.png)

Thank you for your patience with my problem.

**Comment by mro** [comment] 2020-03-22 15:42
apologies for the long delay, plz reopen if still an issue.

**Closed by mro** 2020-03-22 15:42 UTC
Labels: invalid
